<?php

namespace ContainerMEsv1Qw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K4u_6v3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k4u.6v3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k4u.6v3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'product' => ['privates', '.errored..service_locator.k4u.6v3.App\\Entity\\Products', NULL, 'Cannot autowire service ".service_locator.k4u.6v3": it needs an instance of "App\\Entity\\Products" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'product' => 'App\\Entity\\Products',
        ]);
    }
}
