<?php

namespace ContainerMEsv1Qw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EvlC6rzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EvlC6rz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EvlC6rz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'transportersRepository' => ['privates', 'App\\Repository\\TransportersRepository', 'getTransportersRepositoryService', true],
        ], [
            'transportersRepository' => 'App\\Repository\\TransportersRepository',
        ]);
    }
}
