<?php

namespace ContainerMEsv1Qw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProducts3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.k4u.6v3.App\Entity\Products' shared service.
     *
     * @return \App\Entity\Products
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.k4u.6v3": it needs an instance of "App\\Entity\\Products" but this type has been excluded in "config/services.yaml".');
    }
}
