<?php

namespace ContainerNUzoKR8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransportersService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.X4QVtQa.App\Entity\Transporters' shared service.
     *
     * @return \App\Entity\Transporters
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.X4QVtQa": it needs an instance of "App\\Entity\\Transporters" but this type has been excluded in "config/services.yaml".');
    }
}
