<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMEsv1Qw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMEsv1Qw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMEsv1Qw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMEsv1Qw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMEsv1Qw\App_KernelDevDebugContainer([
    'container.build_hash' => 'MEsv1Qw',
    'container.build_id' => '503f423a',
    'container.build_time' => 1686180609,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMEsv1Qw');
